use_frameworks!

platform :ios, '10.0'

target 'StateMachinePageKit_Example' do
  pod 'StateMachinePageKit', :path => '../'

  target 'StateMachinePageKit_Tests' do
    inherit! :search_paths

    
  end
end
